vertx:
  di:
    scope:
      thread-local:
        cleanup-checker-period: 7.2s
  event-bus:
    codec:
      kryo:
        enabled: true
        type: com.dburyak.vertx.eventbus.kryo.LocalAwareKryoUnsafeMessageCodec
        default: true
        defaultTypes: com.dburyak.vertx.eventbus.VisibleObject
      kryo-copying:
        enabled: true
        type: com.dburyak.vertx.eventbus.kryo.LocalAwareKryoCopyingMessageCodec
        default: true
        defaultTypes:
          - com.dburyak.vertx.test.SampleDtoOne
          - com.dburyak.vertx.test.SampleDtoTwo

  gcp:
    config:
      secret-manager:
        enabled: true
        secret-config-options:
          app.test.secret-1: dmytro-test-secret-1
          app.test.secret-2: dmytro-test-secret-2
