vertx:
  di:
    scope:
      thread-local:
        cleanup-checker-period: 7.2s
  event-bus:
    codec:
      json-unsafe:
        enabled: true
        type: com.dburyak.vertx.eventbus.LocalAwareJsonUnsafeMessageCodec
        default: true
        defaultType: java.lang.Object
      json-copying:
        enabled: true
        type: com.dburyak.vertx.eventbus.LocalAwareJsonCopyingMessageCodec
      sample-dto-json:
        enabled: true
        type: com.dburyak.vertx.eventbus.LocalAwareJsonCopyingMessageCodec
        default: true
        defaultType: com.dburyak.vertx.test.SampleDto
