vertx:
  di:
    scope:
      thread-local:
        cleanup-checker-period: 7.2s
  event-bus:
    codec:
      json:
        enabled: true
        type: com.dburyak.vertx.eventbus.LocalAwareJsonUnsafeMessageCodec
        default: true
        defaultTypes: com.dburyak.vertx.eventbus.VisibleObject
      json-copying:
        enabled: true
        type: com.dburyak.vertx.eventbus.LocalAwareJsonCopyingMessageCodec
        default: true
        defaultTypes:
          - com.dburyak.vertx.test.SampleDtoOne
          - com.dburyak.vertx.test.SampleDtoTwo
