vertx:
  di:
    scope:
      thread-local:
        cleanup-checker-period: 7.2s
  event-bus:
    codec:
      kryo:
        enabled: true
        type: com.dburyak.vertx.eventbus.kryo.LocalAwareKryoUnsafeMessageCodec
        default: true
        defaultTypes: com.dburyak.vertx.eventbus.VisibleObject
      kryo-copying:
        enabled: true
        type: com.dburyak.vertx.eventbus.kryo.LocalAwareKryoCopyingMessageCodec
        default: true
        defaultTypes:
          - com.dburyak.vertx.test.SampleDtoOne
          - com.dburyak.vertx.test.SampleDtoTwo

  gcp:
    config:
      secret-manager:
        enabled: true
        secret-config-options:
          - config-option: app.test.secret-1
            secret-name: dmytro-test-secret-1
            project-id: kuznya-build
            notification-subscription: dmytro-test-secret-1-sub
          - config-option: app.test.secret-2
            secret-name: dmytro-test-secret-2
            project-id: kuznya-build
            notification-subscription: dmytro-test-secret-2-sub
          - config-option: app.test.secret-3
            secret-name: dmytro-test-secret-3
            project-id: kuznya-d
            notification-subscription: dmytro-test-secret-3-sub
